create table 프로젝트 (
    pno int primary key auto_increment,
    mno int not null,
    type varchar(50) not null,
    purpose varchar(50) not null,
    title varchar(30) not null,
    industryArea varchar(50) default '',
    category varchar(20) not null,
    area varchar(60) not null,
    position varchar(100) default '',
    projectStatus varchar(50) not null,
    detailStatus varchar(50) default '',
    detailTask varchar(6000) not null,
    skillStack varchar(50) default '',
    skillStackUse varchar(20) default '',
    availableBudget varchar(50) not null,
    budgetNego varchar(20) default '',
    budgetLater varchar(20) default '',
    projectStartDate datetime,
    projectTerm int not null,
    preMeetingType varchar(20) not null,
    meetingType varchar(20) default '',
    meetingTerm varchar(20) default '',
    workPlace varchar(200) not null,
    workingHours varchar(50) not null,
    extraWorkAndSupport varchar(200) not null,
    deadLine datetime,
    supportBusiness varchar(20) not null,
    prerequisites varchar(100) default '',
    question varchar(200) default '',
    hireType varchar(50) not null,
    employeeState varchar(50) not null,
    managingExperience varchar(50) not null,
    futurePlan varchar(50) default '',
    projectPriority varchar(50) default '',
    interestProduct varchar(50) default '',
    regdate timestamp default current_timestamp,
    fname1 varchar(100),
    fsize1 varchar(5),
    ftype1 varchar(5),
    fname2 varchar(100),
    fsize2 varchar(5),
    ftype2 varchar(5),
    fname3 varchar(100),
    fsize3 varchar(5),
    ftype3 varchar(5),
    fuuid varchar(30)
);




create table 프로젝트상황(
    pno int,
    mno int
);
